apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: data-script
  name: data-script
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data-script
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: data-script
    spec:
      containers:
        - image: nur0709/quotes-data-script:v2
          name: data-script
          env:
          - name: MYSQL_DB_HOST
            valueFrom:
              secretKeyRef:
                name: data-script-secret
                key: MYSQL_DB_HOST
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: data-script-secret
                key: MYSQL_USER
          - name: MYSQL_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: data-script-secret
                key: MYSQL_USER_PASSWORD
        - name: data-script-init-container
          image: busybox:latest
          env:
          - name: MYSQL_DB_HOST
            valueFrom:
              secretKeyRef:
                name: data-script-secret
                key: MYSQL_DB_HOST
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: data-script-secret
                key: MYSQL_USER
          - name: MYSQL_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: data-script-secret
                key: MYSQL_USER_PASSWORD
          command: ['sh', '-c', "until mysql -h ${MYSQL_DB_HOST} -u ${MYSQL_USER} -p${MYSQL_USER_PASSWORD} -e 'show databases;'; do echo waiting for mydb; sleep 2; done"]
          resources: {}
      restartPolicy: Always
status: {}
